/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bpbbank.pasqyra.servisi;

import com.bpbbank.ClientReport;
import com.bpbbank.pasqyra.service.ServiceImpl;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author rinor.jashari
 */
public class MainFrame extends javax.swing.JFrame {

    boolean gabimPeriodStart = false;
    boolean gabimPeriodEnd = false;
    private String exGabimDatat;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulli = new javax.swing.JLabel();
        txtDataEFillimit = new javax.swing.JTextField();
        labelDataEFillimit = new javax.swing.JLabel();
        labelDataEMbarimit = new javax.swing.JLabel();
        txtDataEMbarimit = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        labelNrLlogarise = new javax.swing.JLabel();
        txtNrLlogarise = new javax.swing.JTextField();
        labelValuta = new javax.swing.JLabel();
        txtValuta = new javax.swing.JTextField();
        btnGjeneroPdf = new javax.swing.JButton();
        btnPastroKolonat = new javax.swing.JButton();
        labelExceptions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulli.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Titulli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulli.setText("Pasqyra e klientit");
        Titulli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtDataEFillimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataEFillimitActionPerformed(evt);
            }
        });

        labelDataEFillimit.setText("Data e transferit:");

        labelDataEMbarimit.setText("Data e valutes :");

        txtDataEMbarimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataEMbarimitActionPerformed(evt);
            }
        });

        labelId.setText("ID e klientit:");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        labelNrLlogarise.setText("Numri i llogarise:");

        txtNrLlogarise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrLlogariseActionPerformed(evt);
            }
        });

        labelValuta.setText("Valuta:");

        btnGjeneroPdf.setText("Gjenero Pasqyren");
        btnGjeneroPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGjeneroPdfActionPerformed(evt);
            }
        });

        btnPastroKolonat.setText("Fshij kolonat");
        btnPastroKolonat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastroKolonatActionPerformed(evt);
            }
        });

        labelExceptions.setForeground(new java.awt.Color(255, 0, 0));
        labelExceptions.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelExceptions.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        labelExceptions.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                labelExceptionsPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelNrLlogarise, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDataEMbarimit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDataEMbarimit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNrLlogarise, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelDataEFillimit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Titulli)
                                    .addComponent(txtDataEFillimit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGjeneroPdf)
                            .addComponent(btnPastroKolonat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulli, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataEFillimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataEFillimit)
                    .addComponent(btnGjeneroPdf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataEMbarimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataEMbarimit)
                    .addComponent(btnPastroKolonat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNrLlogarise)
                    .addComponent(txtNrLlogarise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValuta)
                    .addComponent(txtValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGjeneroPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGjeneroPdfActionPerformed
        // TODO add your handling code here:
         String periodStart= txtDataEFillimit.getText();
         String periodEnd = txtDataEMbarimit.getText();
         labelExceptions.setText("Pdf u gjenerua me sukses");
         String id = txtId.getText();
         String account = txtNrLlogarise.getText();
         String value = txtValuta.getText();
         
//         LOGGER.info("Starting the application up!");
        Properties properties = new Properties();
        SendMail sendMail = new SendMail();
        ClientReport cp = new ClientReport();
        if(periodStart == null || periodEnd == null|| id == null|| account == null || value == null){
            labelExceptions.setText("Duhet te plotesoni te gjitha kolonat\n");
        }
       
        
        try{
            
            properties.load(MainFrame.class.getClassLoader().getResourceAsStream("application.properties"));
            String baseLocationForPdfs = properties.getProperty("baseLocationForPdfs");
            String daySpecificLocation = MainFrame.getDate();
            String folderDate;
            folderDate = MainFrame.getDate();
//            folderDate = "13_09_2017";//test
          
            
            boolean exceptionData = MainFrame.compareDate(periodStart, periodEnd);
            labelExceptions.setText(exGabimDatat);
            if(exceptionData){
                labelExceptions.setText("Data e transaksionit duhet te jete me e vogel se data e valutes\n");
            }
            else{
            //1008419236 70433736
            // 1300003300014778 1300001001505494

            String folderPath = baseLocationForPdfs+folderDate;
            System.out.println(folderPath);
            boolean isFolder = new File(folderPath).exists();
            
            
//            String daySpecificLocation = "12_09_2017";//Main.getDate();
            String saveFolder;
            if(isFolder){
                ServiceImpl serviceImpl = new ServiceImpl();
                ClientReport cr = serviceImpl.getClientMonthlyReport(periodStart, periodEnd, id, account, value);
                if(serviceImpl.getExceptions()!= null){
                    labelExceptions.setText("Pasqyra per vlerat e shkruara nuk u gjet,\n rishikoni vlerat");
                }else{
                GjeneratorPDF gjeneratorPdf = new GjeneratorPDF(baseLocationForPdfs+folderDate+"\\",daySpecificLocation,periodStart, periodEnd);
            
               gjeneratorPdf.gjeneroPdf(cr);
               labelExceptions.setText("Pdf u gjenerua me sukses");
            
            String filename = gjeneratorPdf.getFileName();
            //            sendMail.SendEmail(filename); // ben dergimin e file-it me email, ka problem ne lidhjen me local
                
                }
            } else {
                saveFolder = MainFrame.createFolder(folderDate, baseLocationForPdfs);
                ServiceImpl serviceImpl = new ServiceImpl();

                ClientReport cr = serviceImpl.getClientMonthlyReport(periodStart, periodEnd, id, account, value);
                GjeneratorPDF gjeneratorPdf = new GjeneratorPDF(baseLocationForPdfs+saveFolder+"\\",daySpecificLocation,periodStart, periodEnd);
                gjeneratorPdf.gjeneroPdf(cr);
                labelExceptions.setText("Pdf u gjenerua me sukses");
                String filename = gjeneratorPdf.getFileName();
//                  sendMail.SendEmail(filename); // ben dergimin e file-it me email, ka problem ne lidhjen me local
            }
            
            }
           
        
        }
        catch(ParseException pe){
           
            labelExceptions.setText("Formati i datave eshte shtypur gabim.\n "
                    + "Formati duhet te jete yyyy.mm.dd (p.sh 2017.08.25)");
            
        }
        
        catch(SQLException e)
        {
            
            String message = e.getMessage();
            e.printStackTrace();
            labelExceptions.setText(message);
            
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            String msg = ex.getMessage();
            labelExceptions.setText(msg);
        }
        
         
    }//GEN-LAST:event_btnGjeneroPdfActionPerformed
    
    private void txtDataEFillimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataEFillimitActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtDataEFillimitActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtDataEMbarimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataEMbarimitActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDataEMbarimitActionPerformed

    private void txtNrLlogariseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrLlogariseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrLlogariseActionPerformed

    private void btnPastroKolonatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastroKolonatActionPerformed
        // TODO add your handling code here:
        txtDataEFillimit.setText("");
        txtDataEMbarimit.setText("");
        txtId.setText("");
        txtNrLlogarise.setText("");
        txtValuta.setText("");
        labelExceptions.setText("");
        
    }//GEN-LAST:event_btnPastroKolonatActionPerformed

    private void labelExceptionsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_labelExceptionsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_labelExceptionsPropertyChange
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
            }
        });
    }
    
    private static String fileLocation(){
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        String filePath;
        chooser.showOpenDialog(null);
            
            File file = chooser.getSelectedFile();
            filePath = file.getAbsolutePath();
        
        return filePath+"\\";
    }
    private static String getDate(){
        
        Date date = new Date();
        
        SimpleDateFormat ft = new SimpleDateFormat ("dd_MM_yyyy");
        return ft.format(date);
    }
    private static String createFolder(String date, String path){
           
            File dir = new File(path+date);
            dir.mkdir();
        
        return date;
    }
    private static Boolean compareDate(String periodStart, String periodEnd) throws ParseException,Exception{
        
        
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy.MM.dd");
        
        Date dateStart = simpleDateFormat.parse(periodStart);
        Date dateEnd = simpleDateFormat.parse(periodEnd);
        
        if(dateEnd.before(dateStart)){
            
         return true;
        }
        return false;
        
    }
    private void isDateCorrectlyFormated(String periodStart, String periodEnd) throws ParseException{
        try{
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy.MM.dd");
        Date d1 = simpleDateFormat.parse(periodStart);
        Date d2 = simpleDateFormat.parse(periodEnd);
        }
        catch(ParseException ex){
            
            ex.getMessage();
            exGabimDatat = "Keni shtypur gabim datat.\n Formati i duhur eshte yyyy.mm.dd (p.sh. 2017.09.12)";
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulli;
    private javax.swing.JButton btnGjeneroPdf;
    private javax.swing.JButton btnPastroKolonat;
    private javax.swing.JLabel labelDataEFillimit;
    private javax.swing.JLabel labelDataEMbarimit;
    private javax.swing.JLabel labelExceptions;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNrLlogarise;
    private javax.swing.JLabel labelValuta;
    private javax.swing.JTextField txtDataEFillimit;
    private javax.swing.JTextField txtDataEMbarimit;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNrLlogarise;
    private javax.swing.JTextField txtValuta;
    // End of variables declaration//GEN-END:variables
}
